baseURL = "https://gradeapocalypse.netlify.app/"
languageCode = "en-us"
title = "Grade Apocalypse"
sectionPagesMenu = "first"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    pre = "<i class='far fa-angry'></i>"
    url = "/about/"
    weight = "100"

  [[menu.main]]
  identifier = "lists"
  name = "lists"
  pre = "<i class='fas fa-marker'></i>"
  url = "/lists/"
  weight = "120"

  [[menu.main]]
  identifier = "links"
  name = "links"
  pre = "<i class='fas fa-bahai'></i>"
  url = "/links/"
  weight = "300"
